previewsEnabled: false
previewsExpireAfterDays: 1

services:
  # App
  - type: web
    name: docbase:app
    rootDir: app/
    buildFilter:
      paths:
        - app/**
    buildCommand: ./scripts/deploy/build.sh
    staticPublishPath: ./dist
    headers:
      - path: /*
        name: X-Frame-Options
        value: sameorigin
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  # API
  - type: web
    name: docbase:api
    runtime: python
    plan: starter
    rootDir: api/
    buildFilter:
      paths:
        - api/**
    startCommand: ./scripts/deploy/start.sh
    buildCommand: ./scripts/deploy/build.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: DATABASE_URL
        fromDatabase:
          name: docbase:db
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: REDIS_HOST
        fromService:
          type: redis
          name: docbase:redis
          property: host
      - key: REDIS_PORT
        fromService:
          type: redis
          name: docbase:redis
          property: port
      - key: REDIS_URL
        fromService:
          type: redis
          name: docbase:redis
          property: connectionString

  - type: redis
    name: docbase:redis
    ipAllowList: []

databases:
  - name: docbase:db
    databaseName: docbase
    user: admin
    plan: free
