/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/layout/AppHeader.vue')['default']
    AppMain: typeof import('./src/components/layout/AppMain.vue')['default']
    AppSidebar: typeof import('./src/components/layout/AppSidebar.vue')['default']
    Avatar: typeof import('primevue/avatar')['default']
    Badge: typeof import('primevue/badge')['default']
    Button: typeof import('primevue/button')['default']
    CreateDatabaseDialog: typeof import('./src/components/dialogs/CreateDatabaseDialog.vue')['default']
    CreateWorkspaceDialog: typeof import('./src/components/dialogs/CreateWorkspaceDialog.vue')['default']
    Dialog: typeof import('primevue/dialog')['default']
    EditWorkspaceDialog: typeof import('./src/components/dialogs/EditWorkspaceDialog.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Menu: typeof import('primevue/menu')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    ThemeSwitcher: typeof import('./src/components/ThemeSwitcher.vue')['default']
    UiAvatar: typeof import('./src/components/ui/UiAvatar.vue')['default']
    UserAvatar: typeof import('./src/components/ui/UserAvatar.vue')['default']
    XAvatar: typeof import('./src/components/ui/XAvatar.vue')['default']
  }
  export interface ComponentCustomProperties {
    Ripple: typeof import('primevue/ripple')['default']
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
