/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/layout/AppHeader.vue')['default']
    AppMain: typeof import('./src/components/layout/AppMain.vue')['default']
    AppSidebar: typeof import('./src/components/layout/AppSidebar.vue')['default']
    AutoComplete: typeof import('primevue/autocomplete')['default']
    Avatar: typeof import('./src/components/realtime/Avatar.vue')['default']
    AvatarGroup: typeof import('primevue/avatargroup')['default']
    AvatarStac: typeof import('./src/components/ui/AvatarStac.vue')['default']
    AvatarStack: typeof import('./src/components/ui/AvatarStack.vue')['default']
    AvatarStackOrig: typeof import('./src/components/ui/AvatarStackOrig.vue')['default']
    Badge: typeof import('primevue/badge')['default']
    BlockUI: typeof import('primevue/blockui')['default']
    Button: typeof import('primevue/button')['default']
    ButtonGroup: typeof import('primevue/buttongroup')['default']
    Card: typeof import('primevue/card')['default']
    Chip: typeof import('primevue/chip')['default']
    ConfirmDialog: typeof import('primevue/confirmdialog')['default']
    CreateDatabaseDialog: typeof import('./src/components/dialogs/CreateDatabaseDialog.vue')['default']
    CreateWorkspaceDialog: typeof import('./src/components/dialogs/CreateWorkspaceDialog.vue')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Drawer: typeof import('primevue/drawer')['default']
    EditWorkspaceDialog: typeof import('./src/components/dialogs/EditWorkspaceDialog.vue')['default']
    FloatLabel: typeof import('primevue/floatlabel')['default']
    IconField: typeof import('primevue/iconfield')['default']
    InputGroup: typeof import('primevue/inputgroup')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputText: typeof import('primevue/inputtext')['default']
    MemberAvatar: typeof import('./src/components/realtime/MemberAvatar.vue')['default']
    MemberAvatarStack: typeof import('./src/components/realtime/MemberAvatarStack.vue')['default']
    Menu: typeof import('primevue/menu')['default']
    Panel: typeof import('primevue/panel')['default']
    Popover: typeof import('primevue/popover')['default']
    ProfileView: typeof import('./src/components/dialogs/ProfileView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    SelectButton: typeof import('primevue/selectbutton')['default']
    SplitButton: typeof import('primevue/splitbutton')['default']
    Tab: typeof import('primevue/tab')['default']
    TabList: typeof import('primevue/tablist')['default']
    TabPanel: typeof import('primevue/tabpanel')['default']
    TabPanels: typeof import('primevue/tabpanels')['default']
    Tabs: typeof import('primevue/tabs')['default']
    Tag: typeof import('primevue/tag')['default']
    ThemeSwitcher: typeof import('./src/components/ThemeSwitcher.vue')['default']
    Toast: typeof import('primevue/toast')['default']
    ToggleSwitch: typeof import('primevue/toggleswitch')['default']
    Toolbar: typeof import('primevue/toolbar')['default']
    UiAvatar: typeof import('./src/components/ui/UiAvatar.vue')['default']
    UserAvatar: typeof import('./src/components/ui/UserAvatar.vue')['default']
    UserProfileDialog: typeof import('./src/components/dialogs/UserProfileDialog.vue')['default']
    XAvatar: typeof import('./src/components/ui/XAvatar.vue')['default']
  }
  export interface ComponentCustomProperties {
    Ripple: typeof import('primevue/ripple')['default']
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
