# Generated by Django 5.0.3 on 2024-06-01 01:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="view",
            name="is_default",
        ),
        migrations.AlterField(
            model_name="view",
            name="view_type",
            field=models.IntegerField(
                choices=[
                    (0, "Table"),
                    (10, "Grid"),
                    (20, "List"),
                    (30, "Kanban"),
                    (40, "Calendar"),
                    (100, "Meta Admin"),
                    (101, "Meta Page"),
                ],
                default=0,
            ),
        ),
    ]
