# Generated by Django 5.0.6 on 2024-06-29 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="view",
            name="view_type",
            field=models.IntegerField(
                choices=[
                    (0, "Table"),
                    (10, "Grid"),
                    (20, "List"),
                    (30, "Kanban"),
                    (40, "Calendar"),
                    (101, "Meta Page"),
                ],
                default=0,
            ),
        ),
    ]
