# Generated by Django 5.0.6 on 2024-06-30 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_view_view_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="filefieldconfig",
            old_name="is_multiple",
            new_name="allow_multiple",
        ),
    ]
