# Generated by Django 5.0.6 on 2024-06-30 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_rename_is_multiple_filefieldconfig_allow_multiple"),
    ]

    operations = [
        migrations.AddField(
            model_name="booleanfieldconfig",
            name="display_icon",
            field=models.CharField(
                blank=True,
                choices=[
                    ("check", "Check"),
                    ("cross", "Cross"),
                    ("star", "Star"),
                    ("heart", "Heart"),
                    ("thumbs_up", "Thumbs Up"),
                    ("thumbs_down", "Thumbs Down"),
                ],
                default=None,
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="booleanfieldconfig",
            name="display_format",
            field=models.CharField(
                choices=[
                    ("checkbox", "Checkbox"),
                    ("toggle", "Toggle"),
                    ("icon", "Icon"),
                ],
                default="checkbox",
                max_length=255,
            ),
        ),
    ]
